### ISSUE TITLE
Can you please do the same with zen3d?

### ISSUE THREAD

**Issue by xtronoid** [yushijinhun/three-minifier#5]
I think it would be very nice if you can do similar thing with this wonderfull new chinese library

https://github.com/shawn0326/zen-3d

So many thanks in advance, for now...

**Comment by yushijinhun** [comment]
Sorry. This plugin is intended only for three.js. You can fork this repository and port it to zen-3d yourself.

However, I **strongly discourage** this. The problem this plugin solves is a defect in three.js, which could be avoided in the upstream project. This plugin is a workaround. It's ugly and temporary, and should never become a final solution.

I suggest you take a look at [the related issues in readme](https://github.com/yushijinhun/three-minifier#related-issues--repositories). They should explain why it's so difficult to make three.js slim. **I also recommend you invite zen-3d's developers to join the discussion**, hoping they can solve the problem fundamentally rather than tread in three.js's footsteps.
